zookeeper:
  image: jplock/zookeeper:latest
  hostname: zookeeper
  ports:
    - "2181:2181"
mesos-master:
  #mesosphere/mesos-master:0.27.2-2.0.15.ubuntu1404
  image: lxsameer/mesos:0.28.2.2
  hostname: mesos-master
  entrypoint: [ "mesos-master" ]
  ports:
    - "5050:5050"
  links:
    - zookeeper
  environment:
    - MESOS_CLUSTER=local
    - MESOS_HOSTNAME=mesos-master.docker
    - MESOS_LOG_DIR=/var/log
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_ROLES=public
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_ACLS=file:///mesos-config/acls
    - MESOS_CREDENTIALS=file:///mesos-config/credentials
  volumes:
    - ./resources/mesos-config:/mesos-config
mesos-slave:
  #mesosphere/mesos-slave-dind:0.2.4_mesos-0.27.2_docker-1.8.2_ubuntu-14.04.4
  image: lxsameer/mesos:0.28.2.2
  entrypoint:
    - mesos-slave
  privileged: true
  hostname: mesos-slave
  ports:
    - "5051:5051"
  links:
    - zookeeper
    - mesos-master
  environment:
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu, cgroups/mem
    - MESOS_LOG_DIR=var/log
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_PORT=5051
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
    - MESOS_DOCKER_STOP_TIMEOUT=60secs
    - MESOS_RESOURCES=cpus:4;mem:1280;disk:25600;ports(*):[12000-12999]
marathon-service:
  #  mesosphere/marathon:latest-dev
  image: mesoscloud/marathon:1.1.1-ubuntu-15.04
  expose:
    - "8080"
  links:
    - zookeeper
    - mesos-master
  environment:
    - MARATHON_ZK=zk://zookeeper:2181/marathon
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_DECLINE_OFFER_DURATION=3600000
    - MARATHON_PLUGIN_DIR=/plugins
    - MARATHON_PLUGIN_CONF=/plugin-conf.json
    - MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon
    - MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/marathon.secret
    - MARATHON_MESOS_ROLE=public
  volumes:
    - ./resources/marathon-plugins:/plugins
    - ./resources/marathon.plugin-conf.json:/plugin-conf.json
    - ./resources/marathon.secret:/marathon.secret
eliza:
  image: nginx:latest
  hostname: eliza
  ports:
   - "8080:8080"
  links:
    - marathon-service
  environment:
    - DNSDOCK_ALIAS=marathon.docker
  volumes:
    - ./dist:/usr/share/nginx/html
    - ./resources/eliza.nginx.conf:/etc/nginx/nginx.conf
